"""Generate the workbench mesh as a binary STL.

Why a mesh instead of the primitive boxes the world used: a real bench has an
apron, chamfered edges and inset legs, and those silhouette details are exactly
what a vision model uses to tell "table" from "grey rectangle". It is generated
rather than downloaded so the repository stays self-contained.

Coordinates are the model's own frame with the TOP SURFACE AT z = 0, so the SDF
can place it by putting that origin at the working height. Units are metres.

    python3 meshes/make_table.py
"""

from __future__ import annotations

import struct
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent / "workbench.stl"

TOP_X, TOP_Y, TOP_T = 1.40, 1.80, 0.045      # worktop, thickness
APRON_INSET, APRON_H = 0.09, 0.075           # rail under the top
LEG, LEG_INSET = 0.075, 0.11                 # square legs, inset from corners
HEIGHT = 0.60                                # floor to top surface
CHAMFER = 0.008                              # eased worktop edge


def box(cx: float, cy: float, cz: float, sx: float, sy: float, sz: float) -> np.ndarray:
    """Axis-aligned box as 12 triangles, centred on (cx, cy, cz)."""
    x0, x1 = cx - sx / 2, cx + sx / 2
    y0, y1 = cy - sy / 2, cy + sy / 2
    z0, z1 = cz - sz / 2, cz + sz / 2
    v = np.array([
        [x0, y0, z0], [x1, y0, z0], [x1, y1, z0], [x0, y1, z0],
        [x0, y0, z1], [x1, y0, z1], [x1, y1, z1], [x0, y1, z1],
    ])
    faces = [
        (0, 3, 2), (0, 2, 1),   # bottom
        (4, 5, 6), (4, 6, 7),   # top
        (0, 1, 5), (0, 5, 4),   # -y
        (2, 3, 7), (2, 7, 6),   # +y
        (1, 2, 6), (1, 6, 5),   # +x
        (3, 0, 4), (3, 4, 7),   # -x
    ]
    return np.array([[v[a], v[b], v[c]] for a, b, c in faces])


def frustum(cz: float, sz: float, sx0: float, sy0: float,
            sx1: float, sy1: float) -> np.ndarray:
    """A box whose top face is a different size to its bottom: the chamfer."""
    z0, z1 = cz - sz / 2, cz + sz / 2
    b = [(-sx0 / 2, -sy0 / 2), (sx0 / 2, -sy0 / 2), (sx0 / 2, sy0 / 2), (-sx0 / 2, sy0 / 2)]
    t = [(-sx1 / 2, -sy1 / 2), (sx1 / 2, -sy1 / 2), (sx1 / 2, sy1 / 2), (-sx1 / 2, sy1 / 2)]
    v = np.array([[x, y, z0] for x, y in b] + [[x, y, z1] for x, y in t])
    faces = [
        (0, 3, 2), (0, 2, 1),
        (4, 5, 6), (4, 6, 7),
        (0, 1, 5), (0, 5, 4),
        (2, 3, 7), (2, 7, 6),
        (1, 2, 6), (1, 6, 5),
        (3, 0, 4), (3, 4, 7),
    ]
    return np.array([[v[a], v[b], v[c]] for a, b, c in faces])


def build() -> np.ndarray:
    parts = []

    # Worktop: a thin slab plus a chamfered lip, so the edge catches light
    # rather than reading as an infinitely sharp corner.
    parts.append(box(0, 0, -CHAMFER - (TOP_T - CHAMFER) / 2,
                     TOP_X, TOP_Y, TOP_T - CHAMFER))
    parts.append(frustum(-CHAMFER / 2, CHAMFER,
                         TOP_X, TOP_Y, TOP_X - 2 * CHAMFER, TOP_Y - 2 * CHAMFER))

    # Apron rails just under the top, inset on all four sides.
    apron_z = -TOP_T - APRON_H / 2
    parts.append(box(0, (TOP_Y / 2 - APRON_INSET), apron_z,
                     TOP_X - 2 * APRON_INSET, 0.03, APRON_H))
    parts.append(box(0, -(TOP_Y / 2 - APRON_INSET), apron_z,
                     TOP_X - 2 * APRON_INSET, 0.03, APRON_H))
    parts.append(box((TOP_X / 2 - APRON_INSET), 0, apron_z,
                     0.03, TOP_Y - 2 * APRON_INSET, APRON_H))
    parts.append(box(-(TOP_X / 2 - APRON_INSET), 0, apron_z,
                     0.03, TOP_Y - 2 * APRON_INSET, APRON_H))

    # Four legs from the floor to the underside of the top.
    leg_h = HEIGHT - TOP_T
    leg_z = -TOP_T - leg_h / 2
    for sx in (-1, 1):
        for sy in (-1, 1):
            parts.append(box(sx * (TOP_X / 2 - LEG_INSET),
                             sy * (TOP_Y / 2 - LEG_INSET),
                             leg_z, LEG, LEG, leg_h))

    # Lower stretcher shelf, a detail that reads strongly in silhouette.
    parts.append(box(0, 0, -HEIGHT + 0.14,
                     TOP_X - 2 * LEG_INSET - LEG, TOP_Y - 2 * LEG_INSET - LEG, 0.02))
    return np.concatenate(parts, axis=0)


def write_stl(triangles: np.ndarray, path: Path) -> None:
    """Binary STL. Normals are computed per face; STL has no shared vertices."""
    a = triangles[:, 1] - triangles[:, 0]
    b = triangles[:, 2] - triangles[:, 0]
    normals = np.cross(a, b)
    lengths = np.linalg.norm(normals, axis=1, keepdims=True)
    normals = np.divide(normals, lengths, out=np.zeros_like(normals), where=lengths > 0)

    with path.open("wb") as handle:
        handle.write(b"workbench generated by make_table.py".ljust(80, b"\0"))
        handle.write(struct.pack("<I", len(triangles)))
        for normal, tri in zip(normals, triangles):
            handle.write(struct.pack("<3f", *normal))
            for vertex in tri:
                handle.write(struct.pack("<3f", *vertex))
            handle.write(struct.pack("<H", 0))


def main() -> None:
    triangles = build()
    write_stl(triangles, OUT)
    lo = triangles.reshape(-1, 3).min(axis=0)
    hi = triangles.reshape(-1, 3).max(axis=0)
    print(f"  {OUT.name}: {len(triangles)} triangles, {OUT.stat().st_size // 1024} KB")
    print(f"  bounds x[{lo[0]:.3f},{hi[0]:.3f}] y[{lo[1]:.3f},{hi[1]:.3f}] "
          f"z[{lo[2]:.3f},{hi[2]:.3f}]  (top surface at z=0)")


if __name__ == "__main__":
    main()
